HostBase.h: Add missing include of QObject
Fixes:

/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/honister-qt6/webos-ports/tmp-glibc/work/core2-64-webos-linux/luna-sysmgr-common/3.0.0-3+gitAUTOINC+ae31c22625-r0/git/include/HostBase.h:48:25: error: invalid use of incomplete type 'class QObject'

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>