Drop unneeded ApplicationDescription.h
Having this installed is causing compilation errors with luna-sysmgr:

/home/morphis/work/wop/work/luna-sysmgr/Src/base/LsmUtils.cpp: In function ‘std::string
getResourcePathFromString(const string&, const string&, const string&)’:
/home/morphis/work/wop/work/luna-sysmgr/Src/base/LsmUtils.cpp:68:35: error: ‘class
ApplicationDescription’ has no member named ‘folderPath’
/home/morphis/work/wop/work/luna-sysmgr/Src/base/LsmUtils.cpp:73:23: error: ‘class
ApplicationDescription’ has no member named ‘folderPath’

Signed-off-by: Simon Busch <morphis@gravedo.de>